const cityList = [
  {
    id: 1,
    label: "Kandy",
    value: "kandy",
    areas: [
      "Peradeniya",
      "Gampola",
      "Kundasale",
      "Katugastota",
      "Digana",
      "Galagedara",
      "Deltota",
      "Gelioya",
      "Hewaheta",
      "Kadugannawa",
      "Nawalapitiya",
      "Teldeniya",
      "Udunuwara",
      "Akurana",
      "Ampitiya",
    ],
  },
  {
    id: 2,
    label: "Colombo",
    value: "colombo",
    areas: [
      "Colombo 1",
      "Colombo 2",
      "Colombo 3",
      "Colombo 4",
      "Colombo 5",
      "Colombo 6",
      "Colombo 7",
      "Colombo 8",
      "Colombo 9",
      "Colombo 10",
      "Colombo 11",
      "Colombo 12",
      "Colombo 13",
      "Colombo 14",
      "Colombo 15",
    ],
  },
  {
    id: 3,
    label: "Galle",
    value: "galle",
    areas: [
      "Galle",
      "Ambalangoda",
      "Hikkaduwa",
      "Karapitiya",
      "Unawatuna",
      "Boossa",
      "Gonapinuwala",
      "Habaraduwa",
      "Imaduwa",
      "Nagoda",
      "Thelikada",
      "Akmeemana",
      "Baddegama",
      "Bentota",
      "Elpitiya",
      "Hiniduma",
      "Neluwa",
      "Yakkalamulla",
      "Balapitiya",
    ],
  },
];

export default cityList;
